spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sbbank
    driver-class-name: org.postgresql.Driver
    username: user
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest